//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace OpenBI.Converters.PowerBI.Models.msSchemas.Models.VersionMetadata
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Defines version information about the report definition.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class VersionMetadataRoot
    {

        /// <summary>
        /// Defines the schema to use for an item.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.Always)]
        public string Schema { get; set; } = default!;

        /// <summary>
        /// Defines the report definition version, format of version is major.minor.patch
        /// <br/>- major: &gt;=1
        /// <br/>- minor: &gt;=0
        /// <br/>- patch: always 0
        /// </summary>
        [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.Always)]
        public string Version { get; set; } = default!;

    }
}