//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace OpenBI.Converters.PowerBI.Models.msSchemas.Models.ReportExtension
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReportExtensionEntity
    {

        /// <summary>
        /// Name of the extension entity - must match a name in the semantic model.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Additional measures to include on this entity.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("measures", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<ReportExtensionMeasure> Measures { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReportExtensionMeasure
    {

        /// <summary>
        /// Name of the extension measure - must be unique across the semantic model and other extension measures.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Data type for the measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dataType", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PrimitiveTypeName DataType { get; set; } = default!;

        /// <summary>
        /// Extended data category for the measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dataCategory", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DataCategory { get; set; } = default!;

        /// <summary>
        /// DAX expression for this measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("expression", Required = Newtonsoft.Json.Required.Always)]
        public string Expression { get; set; } = default!;

        /// <summary>
        /// Sets the measure to be hidden.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("hidden", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool Hidden { get; set; } = default!;

        /// <summary>
        /// Format string for this measure in VBA format.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("formatString", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string FormatString { get; set; } = default!;

        /// <summary>
        /// Template information that was used to create this measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("measureTemplate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ReportExtensionMeasureTemplate MeasureTemplate { get; set; } = default!;

        /// <summary>
        /// A description for the measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("description", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Description { get; set; } = default!;

        /// <summary>
        /// Display folder for the measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("displayFolder", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DisplayFolder { get; set; } = default!;

        /// <summary>
        /// Additional annotations to include for this measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("annotations", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<MeasureExtensionAnnotation> Annotations { get; set; } = default!;

        /// <summary>
        /// References to other model measures and extensions used in the DAX of this measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("references", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ExpressionReferences References { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum PrimitiveTypeName
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Binary")]
        Binary = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"Boolean")]
        Boolean = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"Date")]
        Date = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"DateTime")]
        DateTime = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"DateTimeZone")]
        DateTimeZone = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"Decimal")]
        Decimal = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"Double")]
        Double = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"Duration")]
        Duration = 7,


        [System.Runtime.Serialization.EnumMember(Value = @"Integer")]
        Integer = 8,


        [System.Runtime.Serialization.EnumMember(Value = @"Json")]
        Json = 9,


        [System.Runtime.Serialization.EnumMember(Value = @"None")]
        None = 10,


        [System.Runtime.Serialization.EnumMember(Value = @"Null")]
        Null = 11,


        [System.Runtime.Serialization.EnumMember(Value = @"Text")]
        Text = 12,


        [System.Runtime.Serialization.EnumMember(Value = @"Time")]
        Time = 13,


        [System.Runtime.Serialization.EnumMember(Value = @"Variant")]
        Variant = 14,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReportExtensionMeasureTemplate
    {

        /// <summary>
        /// Name of the template.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("daxTemplateName", Required = Newtonsoft.Json.Required.Always)]
        public string DaxTemplateName { get; set; } = default!;

        /// <summary>
        /// Version of the template used.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.Always)]
        public double Version { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class MeasureExtensionAnnotation
    {

        /// <summary>
        /// Unique name for this annotation.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Value for the annotation.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Always)]
        public string Value { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ExpressionReferences
    {

        /// <summary>
        /// False if all references are recognized.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("unrecognizedReferences", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool UnrecognizedReferences { get; set; } = default!;

        /// <summary>
        /// References to model measures and other extensions.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("measures", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<MeasureReference> Measures { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class MeasureReference
    {

        /// <summary>
        /// Name of the schema - leave empty if using model measures. Use name of extension if using other measures from the extension.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Schema { get; set; } = default!;

        /// <summary>
        /// Entity name of the measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("entity", Required = Newtonsoft.Json.Required.Always)]
        public string Entity { get; set; } = default!;

        /// <summary>
        /// Name of the measure.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

    }

    /// <summary>
    /// Defines a report extension and its references.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ReportExtensionRoot
    {

        /// <summary>
        /// Name of the extension.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Entities in the semantic model that are extended.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("entities", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<ReportExtensionEntity> Entities { get; set; } = default!;

        /// <summary>
        /// Defines the schema to use for an item.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.Always)]
        public string Schema { get; set; } = default!;

    }
}