//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace OpenBI.Converters.PowerBI.Models.msSchemas.Models.PagesMetadata
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Defines additional information about the report's pages.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class PagesMetadataRoot
    {

        /// <summary>
        /// Defines the order in which report pages are rendered (page names). If omitted, they will be ordered by display name by default.
        /// <br/>If there are pages in this list, that don't have a corresponding definition, they will be ignored.
        /// <br/>Pages with definitions, but not in this list will be ordered by display name and appended to the end, after pages that exist in this list.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("pageOrder", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> PageOrder { get; set; } = default!;

        /// <summary>
        /// Report will open on this page by default - if omitted, report will open on first page based on order defined by pageOrder semantics.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("activePageName", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ActivePageName { get; set; } = default!;

        /// <summary>
        /// Defines the schema to use for an item.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.Always)]
        public string Schema { get; set; } = default!;

    }
}